server:
  port: 1001
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://freeChildren:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}